### ISSUE TITLE
Создать и настроить разграничения прав по Бит-Финанс

### ISSUE THREAD

**Issue by igorro82** [mushrooms-fb/dst_ural#1]
В базе buhbase_test на сервере 1ctest  настроить профиль казначея с ограничениями доступности по статьям оборотов указанным в регистре сведений БФ.

**Comment by igorro82** [comment]
На тестовой базе сделал огранияения по ЦФО и Статьям оборотов. тестируем.

**Comment by igorro82** [comment]
Загрузка в регистр прав записей из экселя по соответствиям (пользователь, ЦФО, статья оборотов)

**Comment by igorro82** [comment]
Для протокола : 1) Права установки виз для Руководителей ЦФО с привязкой к ЦФО (сделано); 2) Настройка логики прав доступа на уровне записей Инициаторов Заявок и Руководителей ЦФО (сделано, еще нюансы проверю); 3) Загрузка из сводных таблиц прав доступа на уровне записей для всех инициаторов Заявок и Руководителей ЦФО; 4) Формирование новой финансовой структуры (Подразделения - ЦФО) в иерархии, которая выстроена в сводной таблице; 5) Разработать логику интерфейсной доступности для Инициаторов Заявок и Руководителей ЦФО.

Тестируются 1- 4 и готовится 5).

**Comment by igorro82** [comment]
На копии все реализовано, что запрашивали. Тестируют и затем перенос в рабочую базу.

**Comment by igorro82** [comment]
Не согласовывают перенос в рабочую..

**Comment by IEBelokamentsev** [comment]
Месяц прошёл. Ещё согласовывают?

**Comment by igorro82** [comment]
В рабочей базе так и не реализовали. Пока другие приоритеты у клиента. Гришина А. проговаривала с Горелой А.

**Comment by igorro82** [comment]
Запушено на рабочей базе.
