### ISSUE TITLE
Разработать отчет по ТЗ

### ISSUE THREAD

**Issue by KovalevAndrey00** [mushrooms-fb/dst_ural#16]

**Comment by KovalevAndrey00** [comment]
Клиент пока отложил эту задачу

**Comment by igorro82** [comment]
[ТЗ Отчет по ДЗ.xlsx](https://github.com/mushrooms-fb/dst_ural/files/11292295/default.xlsx)

**Comment by igorro82** [comment]
Говорят Актуально и хотят обработину.

**Comment by igorro82** [comment]
Согласовали с фруктами замену исполнителя.

**Comment by igorro82** [comment]
Просрано.
