### ISSUE TITLE
Проблема с заявкой

### ISSUE THREAD

**Issue by wesperTi** [mushrooms-fb/dst_ural#25]
![image](https://github.com/mushrooms-fb/dst_ural/assets/91466606/f2efb8c6-1a5c-4931-b66b-ac0ee5463c5f)

Заявка 2465 от 15.06.2023 Проблема. Сумма без НДС - некорректная, минусовая

**Comment by Serbutorin** [comment]
Зашел проверить ошибку на сервере - все работает правильно, передал Искандеру.
